#!/bin/bash

cd "$(dirname "$0")/pre-commit.d"

for hook in *; do
    if [[ $hook == *.sh ]]; then
        sh $hook # On windows this will be executed using git's integrated bash shell (automatic)
        RESULT=$?
        if [ $RESULT != 0 ]; then
            echo "pre-commit.d/$hook returned non-zero: $RESULT, abort commit"
            exit $RESULT
        fi
    fi
done

exit 0