

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     TextTransform Samples/Packages/com.unity.collections/Unity.Collections/FixedString.tt
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Collections;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Mathematics;
using UnityEngine.Internal;
using UnityEngine;
#if UNITY_PROPERTIES_EXISTS
using Unity.Properties;
#endif

namespace Unity.Collections
{

    // A temporary copy of a struct is made before it is displayed in a C# debugger.
    // However, only the first element of data members with names is copied at this time.
    // Therefore, it's important that all data visible in the debugger, has a name
    // and includes no 'fixed' array. This is why we name every byte in the following struct.

    [Serializable]
    [StructLayout(LayoutKind.Explicit, Size=16)]
    [BurstCompatible]
    public struct FixedBytes16
    {
      [FieldOffset(0)] public byte byte0000;
      [FieldOffset(1)] public byte byte0001;
      [FieldOffset(2)] public byte byte0002;
      [FieldOffset(3)] public byte byte0003;
      [FieldOffset(4)] public byte byte0004;
      [FieldOffset(5)] public byte byte0005;
      [FieldOffset(6)] public byte byte0006;
      [FieldOffset(7)] public byte byte0007;
      [FieldOffset(8)] public byte byte0008;
      [FieldOffset(9)] public byte byte0009;
      [FieldOffset(10)] public byte byte0010;
      [FieldOffset(11)] public byte byte0011;
      [FieldOffset(12)] public byte byte0012;
      [FieldOffset(13)] public byte byte0013;
      [FieldOffset(14)] public byte byte0014;
      [FieldOffset(15)] public byte byte0015;
    }


    // A temporary copy of a struct is made before it is displayed in a C# debugger.
    // However, only the first element of data members with names is copied at this time.
    // Therefore, it's important that all data visible in the debugger, has a name
    // and includes no 'fixed' array. This is why we name every byte in the following struct.

    [Serializable]
    [StructLayout(LayoutKind.Explicit, Size=30)]
    [BurstCompatible]
    public struct FixedBytes30
    {
        [FieldOffset(0)] public FixedBytes16 offset0000;
        [FieldOffset(16)] public byte byte0016;
        [FieldOffset(17)] public byte byte0017;
        [FieldOffset(18)] public byte byte0018;
        [FieldOffset(19)] public byte byte0019;
        [FieldOffset(20)] public byte byte0020;
        [FieldOffset(21)] public byte byte0021;
        [FieldOffset(22)] public byte byte0022;
        [FieldOffset(23)] public byte byte0023;
        [FieldOffset(24)] public byte byte0024;
        [FieldOffset(25)] public byte byte0025;
        [FieldOffset(26)] public byte byte0026;
        [FieldOffset(27)] public byte byte0027;
        [FieldOffset(28)] public byte byte0028;
        [FieldOffset(29)] public byte byte0029;
    }

    // A temporary copy of a struct is made before it is displayed in a C# debugger.
    // However, only the first element of data members with names is copied at this time.
    // Therefore, it's important that all data visible in the debugger, has a name
    // and includes no 'fixed' array. This is why we name every byte in the following struct.

    [Serializable]
    [StructLayout(LayoutKind.Explicit, Size=62)]
    [BurstCompatible]
    public struct FixedBytes62
    {
        [FieldOffset(0)] public FixedBytes16 offset0000;
        [FieldOffset(16)] public FixedBytes16 offset0016;
        [FieldOffset(32)] public FixedBytes16 offset0032;
        [FieldOffset(48)] public byte byte0048;
        [FieldOffset(49)] public byte byte0049;
        [FieldOffset(50)] public byte byte0050;
        [FieldOffset(51)] public byte byte0051;
        [FieldOffset(52)] public byte byte0052;
        [FieldOffset(53)] public byte byte0053;
        [FieldOffset(54)] public byte byte0054;
        [FieldOffset(55)] public byte byte0055;
        [FieldOffset(56)] public byte byte0056;
        [FieldOffset(57)] public byte byte0057;
        [FieldOffset(58)] public byte byte0058;
        [FieldOffset(59)] public byte byte0059;
        [FieldOffset(60)] public byte byte0060;
        [FieldOffset(61)] public byte byte0061;
    }

    // A temporary copy of a struct is made before it is displayed in a C# debugger.
    // However, only the first element of data members with names is copied at this time.
    // Therefore, it's important that all data visible in the debugger, has a name
    // and includes no 'fixed' array. This is why we name every byte in the following struct.

    [Serializable]
    [StructLayout(LayoutKind.Explicit, Size=126)]
    [BurstCompatible]
    public struct FixedBytes126
    {
        [FieldOffset(0)] public FixedBytes16 offset0000;
        [FieldOffset(16)] public FixedBytes16 offset0016;
        [FieldOffset(32)] public FixedBytes16 offset0032;
        [FieldOffset(48)] public FixedBytes16 offset0048;
        [FieldOffset(64)] public FixedBytes16 offset0064;
        [FieldOffset(80)] public FixedBytes16 offset0080;
        [FieldOffset(96)] public FixedBytes16 offset0096;
        [FieldOffset(112)] public byte byte0112;
        [FieldOffset(113)] public byte byte0113;
        [FieldOffset(114)] public byte byte0114;
        [FieldOffset(115)] public byte byte0115;
        [FieldOffset(116)] public byte byte0116;
        [FieldOffset(117)] public byte byte0117;
        [FieldOffset(118)] public byte byte0118;
        [FieldOffset(119)] public byte byte0119;
        [FieldOffset(120)] public byte byte0120;
        [FieldOffset(121)] public byte byte0121;
        [FieldOffset(122)] public byte byte0122;
        [FieldOffset(123)] public byte byte0123;
        [FieldOffset(124)] public byte byte0124;
        [FieldOffset(125)] public byte byte0125;
    }

    // A temporary copy of a struct is made before it is displayed in a C# debugger.
    // However, only the first element of data members with names is copied at this time.
    // Therefore, it's important that all data visible in the debugger, has a name
    // and includes no 'fixed' array. This is why we name every byte in the following struct.

    [Serializable]
    [StructLayout(LayoutKind.Explicit, Size=510)]
    [BurstCompatible]
    public struct FixedBytes510
    {
        [FieldOffset(0)] public FixedBytes16 offset0000;
        [FieldOffset(16)] public FixedBytes16 offset0016;
        [FieldOffset(32)] public FixedBytes16 offset0032;
        [FieldOffset(48)] public FixedBytes16 offset0048;
        [FieldOffset(64)] public FixedBytes16 offset0064;
        [FieldOffset(80)] public FixedBytes16 offset0080;
        [FieldOffset(96)] public FixedBytes16 offset0096;
        [FieldOffset(112)] public FixedBytes16 offset0112;
        [FieldOffset(128)] public FixedBytes16 offset0128;
        [FieldOffset(144)] public FixedBytes16 offset0144;
        [FieldOffset(160)] public FixedBytes16 offset0160;
        [FieldOffset(176)] public FixedBytes16 offset0176;
        [FieldOffset(192)] public FixedBytes16 offset0192;
        [FieldOffset(208)] public FixedBytes16 offset0208;
        [FieldOffset(224)] public FixedBytes16 offset0224;
        [FieldOffset(240)] public FixedBytes16 offset0240;
        [FieldOffset(256)] public FixedBytes16 offset0256;
        [FieldOffset(272)] public FixedBytes16 offset0272;
        [FieldOffset(288)] public FixedBytes16 offset0288;
        [FieldOffset(304)] public FixedBytes16 offset0304;
        [FieldOffset(320)] public FixedBytes16 offset0320;
        [FieldOffset(336)] public FixedBytes16 offset0336;
        [FieldOffset(352)] public FixedBytes16 offset0352;
        [FieldOffset(368)] public FixedBytes16 offset0368;
        [FieldOffset(384)] public FixedBytes16 offset0384;
        [FieldOffset(400)] public FixedBytes16 offset0400;
        [FieldOffset(416)] public FixedBytes16 offset0416;
        [FieldOffset(432)] public FixedBytes16 offset0432;
        [FieldOffset(448)] public FixedBytes16 offset0448;
        [FieldOffset(464)] public FixedBytes16 offset0464;
        [FieldOffset(480)] public FixedBytes16 offset0480;
        [FieldOffset(496)] public byte byte0496;
        [FieldOffset(497)] public byte byte0497;
        [FieldOffset(498)] public byte byte0498;
        [FieldOffset(499)] public byte byte0499;
        [FieldOffset(500)] public byte byte0500;
        [FieldOffset(501)] public byte byte0501;
        [FieldOffset(502)] public byte byte0502;
        [FieldOffset(503)] public byte byte0503;
        [FieldOffset(504)] public byte byte0504;
        [FieldOffset(505)] public byte byte0505;
        [FieldOffset(506)] public byte byte0506;
        [FieldOffset(507)] public byte byte0507;
        [FieldOffset(508)] public byte byte0508;
        [FieldOffset(509)] public byte byte0509;
    }

    // A temporary copy of a struct is made before it is displayed in a C# debugger.
    // However, only the first element of data members with names is copied at this time.
    // Therefore, it's important that all data visible in the debugger, has a name
    // and includes no 'fixed' array. This is why we name every byte in the following struct.

    [Serializable]
    [StructLayout(LayoutKind.Explicit, Size=4094)]
    [BurstCompatible]
    public struct FixedBytes4094
    {
        [FieldOffset(0)] public FixedBytes16 offset0000;
        [FieldOffset(16)] public FixedBytes16 offset0016;
        [FieldOffset(32)] public FixedBytes16 offset0032;
        [FieldOffset(48)] public FixedBytes16 offset0048;
        [FieldOffset(64)] public FixedBytes16 offset0064;
        [FieldOffset(80)] public FixedBytes16 offset0080;
        [FieldOffset(96)] public FixedBytes16 offset0096;
        [FieldOffset(112)] public FixedBytes16 offset0112;
        [FieldOffset(128)] public FixedBytes16 offset0128;
        [FieldOffset(144)] public FixedBytes16 offset0144;
        [FieldOffset(160)] public FixedBytes16 offset0160;
        [FieldOffset(176)] public FixedBytes16 offset0176;
        [FieldOffset(192)] public FixedBytes16 offset0192;
        [FieldOffset(208)] public FixedBytes16 offset0208;
        [FieldOffset(224)] public FixedBytes16 offset0224;
        [FieldOffset(240)] public FixedBytes16 offset0240;
        [FieldOffset(256)] public FixedBytes16 offset0256;
        [FieldOffset(272)] public FixedBytes16 offset0272;
        [FieldOffset(288)] public FixedBytes16 offset0288;
        [FieldOffset(304)] public FixedBytes16 offset0304;
        [FieldOffset(320)] public FixedBytes16 offset0320;
        [FieldOffset(336)] public FixedBytes16 offset0336;
        [FieldOffset(352)] public FixedBytes16 offset0352;
        [FieldOffset(368)] public FixedBytes16 offset0368;
        [FieldOffset(384)] public FixedBytes16 offset0384;
        [FieldOffset(400)] public FixedBytes16 offset0400;
        [FieldOffset(416)] public FixedBytes16 offset0416;
        [FieldOffset(432)] public FixedBytes16 offset0432;
        [FieldOffset(448)] public FixedBytes16 offset0448;
        [FieldOffset(464)] public FixedBytes16 offset0464;
        [FieldOffset(480)] public FixedBytes16 offset0480;
        [FieldOffset(496)] public FixedBytes16 offset0496;
        [FieldOffset(512)] public FixedBytes16 offset0512;
        [FieldOffset(528)] public FixedBytes16 offset0528;
        [FieldOffset(544)] public FixedBytes16 offset0544;
        [FieldOffset(560)] public FixedBytes16 offset0560;
        [FieldOffset(576)] public FixedBytes16 offset0576;
        [FieldOffset(592)] public FixedBytes16 offset0592;
        [FieldOffset(608)] public FixedBytes16 offset0608;
        [FieldOffset(624)] public FixedBytes16 offset0624;
        [FieldOffset(640)] public FixedBytes16 offset0640;
        [FieldOffset(656)] public FixedBytes16 offset0656;
        [FieldOffset(672)] public FixedBytes16 offset0672;
        [FieldOffset(688)] public FixedBytes16 offset0688;
        [FieldOffset(704)] public FixedBytes16 offset0704;
        [FieldOffset(720)] public FixedBytes16 offset0720;
        [FieldOffset(736)] public FixedBytes16 offset0736;
        [FieldOffset(752)] public FixedBytes16 offset0752;
        [FieldOffset(768)] public FixedBytes16 offset0768;
        [FieldOffset(784)] public FixedBytes16 offset0784;
        [FieldOffset(800)] public FixedBytes16 offset0800;
        [FieldOffset(816)] public FixedBytes16 offset0816;
        [FieldOffset(832)] public FixedBytes16 offset0832;
        [FieldOffset(848)] public FixedBytes16 offset0848;
        [FieldOffset(864)] public FixedBytes16 offset0864;
        [FieldOffset(880)] public FixedBytes16 offset0880;
        [FieldOffset(896)] public FixedBytes16 offset0896;
        [FieldOffset(912)] public FixedBytes16 offset0912;
        [FieldOffset(928)] public FixedBytes16 offset0928;
        [FieldOffset(944)] public FixedBytes16 offset0944;
        [FieldOffset(960)] public FixedBytes16 offset0960;
        [FieldOffset(976)] public FixedBytes16 offset0976;
        [FieldOffset(992)] public FixedBytes16 offset0992;
        [FieldOffset(1008)] public FixedBytes16 offset1008;
        [FieldOffset(1024)] public FixedBytes16 offset1024;
        [FieldOffset(1040)] public FixedBytes16 offset1040;
        [FieldOffset(1056)] public FixedBytes16 offset1056;
        [FieldOffset(1072)] public FixedBytes16 offset1072;
        [FieldOffset(1088)] public FixedBytes16 offset1088;
        [FieldOffset(1104)] public FixedBytes16 offset1104;
        [FieldOffset(1120)] public FixedBytes16 offset1120;
        [FieldOffset(1136)] public FixedBytes16 offset1136;
        [FieldOffset(1152)] public FixedBytes16 offset1152;
        [FieldOffset(1168)] public FixedBytes16 offset1168;
        [FieldOffset(1184)] public FixedBytes16 offset1184;
        [FieldOffset(1200)] public FixedBytes16 offset1200;
        [FieldOffset(1216)] public FixedBytes16 offset1216;
        [FieldOffset(1232)] public FixedBytes16 offset1232;
        [FieldOffset(1248)] public FixedBytes16 offset1248;
        [FieldOffset(1264)] public FixedBytes16 offset1264;
        [FieldOffset(1280)] public FixedBytes16 offset1280;
        [FieldOffset(1296)] public FixedBytes16 offset1296;
        [FieldOffset(1312)] public FixedBytes16 offset1312;
        [FieldOffset(1328)] public FixedBytes16 offset1328;
        [FieldOffset(1344)] public FixedBytes16 offset1344;
        [FieldOffset(1360)] public FixedBytes16 offset1360;
        [FieldOffset(1376)] public FixedBytes16 offset1376;
        [FieldOffset(1392)] public FixedBytes16 offset1392;
        [FieldOffset(1408)] public FixedBytes16 offset1408;
        [FieldOffset(1424)] public FixedBytes16 offset1424;
        [FieldOffset(1440)] public FixedBytes16 offset1440;
        [FieldOffset(1456)] public FixedBytes16 offset1456;
        [FieldOffset(1472)] public FixedBytes16 offset1472;
        [FieldOffset(1488)] public FixedBytes16 offset1488;
        [FieldOffset(1504)] public FixedBytes16 offset1504;
        [FieldOffset(1520)] public FixedBytes16 offset1520;
        [FieldOffset(1536)] public FixedBytes16 offset1536;
        [FieldOffset(1552)] public FixedBytes16 offset1552;
        [FieldOffset(1568)] public FixedBytes16 offset1568;
        [FieldOffset(1584)] public FixedBytes16 offset1584;
        [FieldOffset(1600)] public FixedBytes16 offset1600;
        [FieldOffset(1616)] public FixedBytes16 offset1616;
        [FieldOffset(1632)] public FixedBytes16 offset1632;
        [FieldOffset(1648)] public FixedBytes16 offset1648;
        [FieldOffset(1664)] public FixedBytes16 offset1664;
        [FieldOffset(1680)] public FixedBytes16 offset1680;
        [FieldOffset(1696)] public FixedBytes16 offset1696;
        [FieldOffset(1712)] public FixedBytes16 offset1712;
        [FieldOffset(1728)] public FixedBytes16 offset1728;
        [FieldOffset(1744)] public FixedBytes16 offset1744;
        [FieldOffset(1760)] public FixedBytes16 offset1760;
        [FieldOffset(1776)] public FixedBytes16 offset1776;
        [FieldOffset(1792)] public FixedBytes16 offset1792;
        [FieldOffset(1808)] public FixedBytes16 offset1808;
        [FieldOffset(1824)] public FixedBytes16 offset1824;
        [FieldOffset(1840)] public FixedBytes16 offset1840;
        [FieldOffset(1856)] public FixedBytes16 offset1856;
        [FieldOffset(1872)] public FixedBytes16 offset1872;
        [FieldOffset(1888)] public FixedBytes16 offset1888;
        [FieldOffset(1904)] public FixedBytes16 offset1904;
        [FieldOffset(1920)] public FixedBytes16 offset1920;
        [FieldOffset(1936)] public FixedBytes16 offset1936;
        [FieldOffset(1952)] public FixedBytes16 offset1952;
        [FieldOffset(1968)] public FixedBytes16 offset1968;
        [FieldOffset(1984)] public FixedBytes16 offset1984;
        [FieldOffset(2000)] public FixedBytes16 offset2000;
        [FieldOffset(2016)] public FixedBytes16 offset2016;
        [FieldOffset(2032)] public FixedBytes16 offset2032;
        [FieldOffset(2048)] public FixedBytes16 offset2048;
        [FieldOffset(2064)] public FixedBytes16 offset2064;
        [FieldOffset(2080)] public FixedBytes16 offset2080;
        [FieldOffset(2096)] public FixedBytes16 offset2096;
        [FieldOffset(2112)] public FixedBytes16 offset2112;
        [FieldOffset(2128)] public FixedBytes16 offset2128;
        [FieldOffset(2144)] public FixedBytes16 offset2144;
        [FieldOffset(2160)] public FixedBytes16 offset2160;
        [FieldOffset(2176)] public FixedBytes16 offset2176;
        [FieldOffset(2192)] public FixedBytes16 offset2192;
        [FieldOffset(2208)] public FixedBytes16 offset2208;
        [FieldOffset(2224)] public FixedBytes16 offset2224;
        [FieldOffset(2240)] public FixedBytes16 offset2240;
        [FieldOffset(2256)] public FixedBytes16 offset2256;
        [FieldOffset(2272)] public FixedBytes16 offset2272;
        [FieldOffset(2288)] public FixedBytes16 offset2288;
        [FieldOffset(2304)] public FixedBytes16 offset2304;
        [FieldOffset(2320)] public FixedBytes16 offset2320;
        [FieldOffset(2336)] public FixedBytes16 offset2336;
        [FieldOffset(2352)] public FixedBytes16 offset2352;
        [FieldOffset(2368)] public FixedBytes16 offset2368;
        [FieldOffset(2384)] public FixedBytes16 offset2384;
        [FieldOffset(2400)] public FixedBytes16 offset2400;
        [FieldOffset(2416)] public FixedBytes16 offset2416;
        [FieldOffset(2432)] public FixedBytes16 offset2432;
        [FieldOffset(2448)] public FixedBytes16 offset2448;
        [FieldOffset(2464)] public FixedBytes16 offset2464;
        [FieldOffset(2480)] public FixedBytes16 offset2480;
        [FieldOffset(2496)] public FixedBytes16 offset2496;
        [FieldOffset(2512)] public FixedBytes16 offset2512;
        [FieldOffset(2528)] public FixedBytes16 offset2528;
        [FieldOffset(2544)] public FixedBytes16 offset2544;
        [FieldOffset(2560)] public FixedBytes16 offset2560;
        [FieldOffset(2576)] public FixedBytes16 offset2576;
        [FieldOffset(2592)] public FixedBytes16 offset2592;
        [FieldOffset(2608)] public FixedBytes16 offset2608;
        [FieldOffset(2624)] public FixedBytes16 offset2624;
        [FieldOffset(2640)] public FixedBytes16 offset2640;
        [FieldOffset(2656)] public FixedBytes16 offset2656;
        [FieldOffset(2672)] public FixedBytes16 offset2672;
        [FieldOffset(2688)] public FixedBytes16 offset2688;
        [FieldOffset(2704)] public FixedBytes16 offset2704;
        [FieldOffset(2720)] public FixedBytes16 offset2720;
        [FieldOffset(2736)] public FixedBytes16 offset2736;
        [FieldOffset(2752)] public FixedBytes16 offset2752;
        [FieldOffset(2768)] public FixedBytes16 offset2768;
        [FieldOffset(2784)] public FixedBytes16 offset2784;
        [FieldOffset(2800)] public FixedBytes16 offset2800;
        [FieldOffset(2816)] public FixedBytes16 offset2816;
        [FieldOffset(2832)] public FixedBytes16 offset2832;
        [FieldOffset(2848)] public FixedBytes16 offset2848;
        [FieldOffset(2864)] public FixedBytes16 offset2864;
        [FieldOffset(2880)] public FixedBytes16 offset2880;
        [FieldOffset(2896)] public FixedBytes16 offset2896;
        [FieldOffset(2912)] public FixedBytes16 offset2912;
        [FieldOffset(2928)] public FixedBytes16 offset2928;
        [FieldOffset(2944)] public FixedBytes16 offset2944;
        [FieldOffset(2960)] public FixedBytes16 offset2960;
        [FieldOffset(2976)] public FixedBytes16 offset2976;
        [FieldOffset(2992)] public FixedBytes16 offset2992;
        [FieldOffset(3008)] public FixedBytes16 offset3008;
        [FieldOffset(3024)] public FixedBytes16 offset3024;
        [FieldOffset(3040)] public FixedBytes16 offset3040;
        [FieldOffset(3056)] public FixedBytes16 offset3056;
        [FieldOffset(3072)] public FixedBytes16 offset3072;
        [FieldOffset(3088)] public FixedBytes16 offset3088;
        [FieldOffset(3104)] public FixedBytes16 offset3104;
        [FieldOffset(3120)] public FixedBytes16 offset3120;
        [FieldOffset(3136)] public FixedBytes16 offset3136;
        [FieldOffset(3152)] public FixedBytes16 offset3152;
        [FieldOffset(3168)] public FixedBytes16 offset3168;
        [FieldOffset(3184)] public FixedBytes16 offset3184;
        [FieldOffset(3200)] public FixedBytes16 offset3200;
        [FieldOffset(3216)] public FixedBytes16 offset3216;
        [FieldOffset(3232)] public FixedBytes16 offset3232;
        [FieldOffset(3248)] public FixedBytes16 offset3248;
        [FieldOffset(3264)] public FixedBytes16 offset3264;
        [FieldOffset(3280)] public FixedBytes16 offset3280;
        [FieldOffset(3296)] public FixedBytes16 offset3296;
        [FieldOffset(3312)] public FixedBytes16 offset3312;
        [FieldOffset(3328)] public FixedBytes16 offset3328;
        [FieldOffset(3344)] public FixedBytes16 offset3344;
        [FieldOffset(3360)] public FixedBytes16 offset3360;
        [FieldOffset(3376)] public FixedBytes16 offset3376;
        [FieldOffset(3392)] public FixedBytes16 offset3392;
        [FieldOffset(3408)] public FixedBytes16 offset3408;
        [FieldOffset(3424)] public FixedBytes16 offset3424;
        [FieldOffset(3440)] public FixedBytes16 offset3440;
        [FieldOffset(3456)] public FixedBytes16 offset3456;
        [FieldOffset(3472)] public FixedBytes16 offset3472;
        [FieldOffset(3488)] public FixedBytes16 offset3488;
        [FieldOffset(3504)] public FixedBytes16 offset3504;
        [FieldOffset(3520)] public FixedBytes16 offset3520;
        [FieldOffset(3536)] public FixedBytes16 offset3536;
        [FieldOffset(3552)] public FixedBytes16 offset3552;
        [FieldOffset(3568)] public FixedBytes16 offset3568;
        [FieldOffset(3584)] public FixedBytes16 offset3584;
        [FieldOffset(3600)] public FixedBytes16 offset3600;
        [FieldOffset(3616)] public FixedBytes16 offset3616;
        [FieldOffset(3632)] public FixedBytes16 offset3632;
        [FieldOffset(3648)] public FixedBytes16 offset3648;
        [FieldOffset(3664)] public FixedBytes16 offset3664;
        [FieldOffset(3680)] public FixedBytes16 offset3680;
        [FieldOffset(3696)] public FixedBytes16 offset3696;
        [FieldOffset(3712)] public FixedBytes16 offset3712;
        [FieldOffset(3728)] public FixedBytes16 offset3728;
        [FieldOffset(3744)] public FixedBytes16 offset3744;
        [FieldOffset(3760)] public FixedBytes16 offset3760;
        [FieldOffset(3776)] public FixedBytes16 offset3776;
        [FieldOffset(3792)] public FixedBytes16 offset3792;
        [FieldOffset(3808)] public FixedBytes16 offset3808;
        [FieldOffset(3824)] public FixedBytes16 offset3824;
        [FieldOffset(3840)] public FixedBytes16 offset3840;
        [FieldOffset(3856)] public FixedBytes16 offset3856;
        [FieldOffset(3872)] public FixedBytes16 offset3872;
        [FieldOffset(3888)] public FixedBytes16 offset3888;
        [FieldOffset(3904)] public FixedBytes16 offset3904;
        [FieldOffset(3920)] public FixedBytes16 offset3920;
        [FieldOffset(3936)] public FixedBytes16 offset3936;
        [FieldOffset(3952)] public FixedBytes16 offset3952;
        [FieldOffset(3968)] public FixedBytes16 offset3968;
        [FieldOffset(3984)] public FixedBytes16 offset3984;
        [FieldOffset(4000)] public FixedBytes16 offset4000;
        [FieldOffset(4016)] public FixedBytes16 offset4016;
        [FieldOffset(4032)] public FixedBytes16 offset4032;
        [FieldOffset(4048)] public FixedBytes16 offset4048;
        [FieldOffset(4064)] public FixedBytes16 offset4064;
        [FieldOffset(4080)] public byte byte4080;
        [FieldOffset(4081)] public byte byte4081;
        [FieldOffset(4082)] public byte byte4082;
        [FieldOffset(4083)] public byte byte4083;
        [FieldOffset(4084)] public byte byte4084;
        [FieldOffset(4085)] public byte byte4085;
        [FieldOffset(4086)] public byte byte4086;
        [FieldOffset(4087)] public byte byte4087;
        [FieldOffset(4088)] public byte byte4088;
        [FieldOffset(4089)] public byte byte4089;
        [FieldOffset(4090)] public byte byte4090;
        [FieldOffset(4091)] public byte byte4091;
        [FieldOffset(4092)] public byte byte4092;
        [FieldOffset(4093)] public byte byte4093;
    }
}
