using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

namespace UnityEngine.Experimental.Rendering.HDPipeline
{
    [Serializable]
    public class GlobalDebugParameters
    {
        public float debugOverlayRatio = 0.33f;
        public bool displayDebug = false;
        public bool displayRenderingDebug = false;
        public bool displayLightingDebug = false;

        public LightingDebugParameters lightingDebugParameters = new LightingDebugParameters();
        public RenderingDebugParameters renderingDebugParametrs = new RenderingDebugParameters();
    }

    [Serializable]
    public class RenderingDebugParameters
    {
        public bool displayOpaqueObjects = true;
        public bool displayTransparentObjects = true;
        public bool enableDistortion = true;
    }

    public class DebugParameters
    {
        // Material Debugging
        public int debugViewMaterial = 0;

        // Rendering debugging

        public bool useForwardRenderingOnly = false; // TODO: Currently there is no way to strip the extra forward shaders generated by the shaders compiler, so we can switch dynamically.
        public bool useDepthPrepass = false;

        // we have to fallback to forward-only rendering when scene view is using wireframe rendering mode --
        // as rendering everything in wireframe + deferred do not play well together
        public bool ShouldUseForwardRenderingOnly() { return useForwardRenderingOnly || GL.wireframe; }
    }

    public enum ShadowDebugMode
    {
        None,
        VisualizeAtlas,
        VisualizeShadowMap
    }

    public enum LightingDebugMode
    {
        None,
        DiffuseLighting,
        SpecularLighting
    }

    [Serializable]
    public class LightingDebugParameters
    {
        public bool                 enableShadows = true;
        public ShadowDebugMode      visualizationMode = ShadowDebugMode.None;
        public uint                 visualizeShadowMapIndex = 0;

        public LightingDebugMode    lightingDebugMode = LightingDebugMode.None;
        public bool                 overrideSmoothness = false;
        public float                overrideSmoothnessValue = 1.0f;
        public Color                debugLightingAlbedo = new Color(0.5f, 0.5f, 0.5f);
    }
}
