#ifndef UNITY_LIGHT_TRANSMITTANCE_VARIABLES_INCLUDED
#define UNITY_LIGHT_TRANSMITTANCE_VARIABLES_INCLUDED

CBUFFER_START(UnityVolumetricShadowMap)
    uint  _VShadowMapRes;
    float _VShadowMapMag;
CBUFFER_END

#endif // UNITY_VOLUMETRIC_SHADOWMAP_VARIABLES_INCLUDED
