comment:
  on-update: edit
  header: |
    Hi! This comment will help you figure out which jobs to run before merging your PR. The suggestions are dynamic based on what files you have changed.
    Link to Yamato: https://unity-ci.cds.internal.unity3d.com/project/902/
    Search for your PR branch using the search bar at the top, then add the following segment(s) to the end of the URL (you may need multiple tabs depending on how many packages you change)
  footer: |
    Depending on the scope of your PR, you may need to run more jobs than what has been suggested. Please speak to your lead or a Graphics SDET (#devs-graphics-automation) if you are unsure.

  snippets:
    - id: HDRP
      files:
        - com.unity.render-pipelines.high-definition-config/**/*
        - com.unity.render-pipelines.high-definition/**/*
        - com.unity.testing.hdrp/**/*
        - TestProjects/HDRP*/**/*
      body: |
        **HDRP**
        `/jobDefinition/.yamato%2Fall-hdrp.yml%23HDRP_trunk`
        With changes to HDRP packages, you should also run
        `/jobDefinition/.yamato%252Fall-lightmapper.yml%2523PR_LightMapper_trunk`
    - id: URP
      files:
        - com.unity.render-pipelines.universal/**/*
        - com.unity.testing.urp/**/*
        - TestProjects/Universal*/**/*
      body: |
        **URP**
        `/jobDefinition/.yamato%252Fall-urp.yml%2523PR_URP_trunk`
        With changes to URP packages, you should also run
        `/jobDefinition/.yamato%252Fall-lightmapper.yml%2523PR_LightMapper_trunk`
    - id: ShaderGraph
      files:
        - com.unity.shadergraph/**/*
        - TestProjects/ShaderGraph*/**/*
        - com.unity.render-pipelines.universal/Editor/ShaderGraph/*
      body: |
        **Shader Graph**
        `/jobDefinition/.yamato%252Fall-shadergraph.yml%2523PR_ShaderGraph_trunk`
        Depending on your PR, you may also want
        `/jobDefinition/.yamato%252Fall-shadergraph_builtin_foundation.yml%2523PR_ShaderGraph_BuiltIn_Foundation_trunk`
        `/jobDefinition/.yamato%252Fall-shadergraph_builtin_lighting.yml%2523PR_ShaderGraph_BuiltIn_Lighting_trunk`
    - id: VFX
      files:
        - com.unity.visualeffectgraph/**/*
        - com.unity.testing.visualeffectgraph/**/*
        - TestProjects/VisualEffectGraph*/**/*
      body: |
        **VFX**
        `/jobDefinition/.yamato%252Fall-vfx.yml%2523PR_VFX_trunk`
    - id: Core
      files:
        - com.unity.render-pipelines.core/**/*
      body: |
        **SRP Core**
        You could run ABV on your branch before merging your PR, but it will start A LOT of jobs. Please be responsible about it and run it only when you feel the PR is ready:
        `/jobDefinition/.yamato%252F_abv.yml%2523all_project_ci_trunk`
        Be aware that any modifications to the Core package impacts everyone in the Graphics repo so please discuss the PR with your lead.
