//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef DEBUGDISPLAY_CS_HLSL
#define DEBUGDISPLAY_CS_HLSL
//
// UnityEngine.Rendering.HighDefinition.FullScreenDebugMode:  static fields
//
#define FULLSCREENDEBUGMODE_NONE (0)
#define FULLSCREENDEBUGMODE_MIN_LIGHTING_FULL_SCREEN_DEBUG (1)
#define FULLSCREENDEBUGMODE_SSAO (2)
#define FULLSCREENDEBUGMODE_SCREEN_SPACE_REFLECTIONS (3)
#define FULLSCREENDEBUGMODE_CONTACT_SHADOWS (4)
#define FULLSCREENDEBUGMODE_CONTACT_SHADOWS_FADE (5)
#define FULLSCREENDEBUGMODE_SCREEN_SPACE_SHADOWS (6)
#define FULLSCREENDEBUGMODE_PRE_REFRACTION_COLOR_PYRAMID (7)
#define FULLSCREENDEBUGMODE_DEPTH_PYRAMID (8)
#define FULLSCREENDEBUGMODE_FINAL_COLOR_PYRAMID (9)
#define FULLSCREENDEBUGMODE_LIGHT_CLUSTER (10)
#define FULLSCREENDEBUGMODE_RAY_TRACED_GLOBAL_ILLUMINATION (11)
#define FULLSCREENDEBUGMODE_RECURSIVE_RAY_TRACING (12)
#define FULLSCREENDEBUGMODE_RAY_TRACED_SUB_SURFACE (13)
#define FULLSCREENDEBUGMODE_MAX_LIGHTING_FULL_SCREEN_DEBUG (14)
#define FULLSCREENDEBUGMODE_MIN_RENDERING_FULL_SCREEN_DEBUG (15)
#define FULLSCREENDEBUGMODE_MOTION_VECTORS (16)
#define FULLSCREENDEBUGMODE_NAN_TRACKER (17)
#define FULLSCREENDEBUGMODE_COLOR_LOG (18)
#define FULLSCREENDEBUGMODE_DEPTH_OF_FIELD_COC (19)
#define FULLSCREENDEBUGMODE_TRANSPARENCY_OVERDRAW (20)
#define FULLSCREENDEBUGMODE_MAX_RENDERING_FULL_SCREEN_DEBUG (21)
#define FULLSCREENDEBUGMODE_MIN_MATERIAL_FULL_SCREEN_DEBUG (22)
#define FULLSCREENDEBUGMODE_VALIDATE_DIFFUSE_COLOR (23)
#define FULLSCREENDEBUGMODE_VALIDATE_SPECULAR_COLOR (24)
#define FULLSCREENDEBUGMODE_MAX_MATERIAL_FULL_SCREEN_DEBUG (25)


#endif
