//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef DEBUGDISPLAY_CS_HLSL
#define DEBUGDISPLAY_CS_HLSL
//
// UnityEngine.Experimental.Rendering.HDPipeline.FullScreenDebugMode:  static fields
//
#define FULLSCREENDEBUGMODE_NONE (0)
#define FULLSCREENDEBUGMODE_MIN_LIGHTING_FULL_SCREEN_DEBUG (1)
#define FULLSCREENDEBUGMODE_SSAO (2)
#define FULLSCREENDEBUGMODE_SCREEN_SPACE_REFLECTIONS (3)
#define FULLSCREENDEBUGMODE_CONTACT_SHADOWS (4)
#define FULLSCREENDEBUGMODE_PRE_REFRACTION_COLOR_PYRAMID (5)
#define FULLSCREENDEBUGMODE_DEPTH_PYRAMID (6)
#define FULLSCREENDEBUGMODE_FINAL_COLOR_PYRAMID (7)
#define FULLSCREENDEBUGMODE_LIGHT_CLUSTER (8)
#define FULLSCREENDEBUGMODE_RAYTRACED_AREA_SHADOW (9)
#define FULLSCREENDEBUGMODE_MAX_LIGHTING_FULL_SCREEN_DEBUG (10)
#define FULLSCREENDEBUGMODE_MIN_RENDERING_FULL_SCREEN_DEBUG (11)
#define FULLSCREENDEBUGMODE_MOTION_VECTORS (12)
#define FULLSCREENDEBUGMODE_NAN_TRACKER (13)
#define FULLSCREENDEBUGMODE_MAX_RENDERING_FULL_SCREEN_DEBUG (14)
#define FULLSCREENDEBUGMODE_MIN_MATERIAL_FULL_SCREEN_DEBUG (15)
#define FULLSCREENDEBUGMODE_VALIDATE_DIFFUSE_COLOR (16)
#define FULLSCREENDEBUGMODE_VALIDATE_SPECULAR_COLOR (17)
#define FULLSCREENDEBUGMODE_MAX_MATERIAL_FULL_SCREEN_DEBUG (18)


#endif
