//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef LIGHTINGDEBUG_CS_HLSL
#define LIGHTINGDEBUG_CS_HLSL
//
// UnityEngine.Experimental.Rendering.HDPipeline.DebugLightingMode:  static fields
//
#define DEBUGLIGHTINGMODE_NONE (0)
#define DEBUGLIGHTINGMODE_DIFFUSE_LIGHTING (1)
#define DEBUGLIGHTINGMODE_SPECULAR_LIGHTING (2)
#define DEBUGLIGHTINGMODE_LUX_METER (3)
#define DEBUGLIGHTINGMODE_LUMINANCE_METER (4)
#define DEBUGLIGHTINGMODE_MATCAP_VIEW (5)
#define DEBUGLIGHTINGMODE_VISUALIZE_CASCADE (6)
#define DEBUGLIGHTINGMODE_VISUALIZE_SHADOW_MASKS (7)
#define DEBUGLIGHTINGMODE_INDIRECT_DIFFUSE_OCCLUSION (8)
#define DEBUGLIGHTINGMODE_INDIRECT_SPECULAR_OCCLUSION (9)

//
// UnityEngine.Experimental.Rendering.HDPipeline.DebugLightFilterMode:  static fields
//
#define DEBUGLIGHTFILTERMODE_NONE (0)
#define DEBUGLIGHTFILTERMODE_DIRECT_DIRECTIONAL (1)
#define DEBUGLIGHTFILTERMODE_DIRECT_PUNCTUAL (2)
#define DEBUGLIGHTFILTERMODE_DIRECT_RECTANGLE (4)
#define DEBUGLIGHTFILTERMODE_DIRECT_TUBE (8)
#define DEBUGLIGHTFILTERMODE_DIRECT_SPOT_CONE (16)
#define DEBUGLIGHTFILTERMODE_DIRECT_SPOT_PYRAMID (32)
#define DEBUGLIGHTFILTERMODE_DIRECT_SPOT_BOX (64)
#define DEBUGLIGHTFILTERMODE_INDIRECT_REFLECTION_PROBE (128)
#define DEBUGLIGHTFILTERMODE_INDIRECT_PLANAR_PROBE (256)

//
// UnityEngine.Experimental.Rendering.HDPipeline.ShadowMapDebugMode:  static fields
//
#define SHADOWMAPDEBUGMODE_NONE (0)
#define SHADOWMAPDEBUGMODE_VISUALIZE_PUNCTUAL_LIGHT_ATLAS (1)
#define SHADOWMAPDEBUGMODE_VISUALIZE_DIRECTIONAL_LIGHT_ATLAS (2)
#define SHADOWMAPDEBUGMODE_VISUALIZE_AREA_LIGHT_ATLAS (3)
#define SHADOWMAPDEBUGMODE_VISUALIZE_SHADOW_MAP (4)
#define SHADOWMAPDEBUGMODE_SINGLE_SHADOW (5)


#endif
