//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef RAYCOUNTMANAGER_CS_HLSL
#define RAYCOUNTMANAGER_CS_HLSL
//
// UnityEngine.Rendering.HighDefinition.RayCountValues:  static fields
//
#define RAYCOUNTVALUES_AMBIENT_OCCLUSION (0)
#define RAYCOUNTVALUES_SHADOW_DIRECTIONAL (1)
#define RAYCOUNTVALUES_SHADOW_POINT_SPOT (2)
#define RAYCOUNTVALUES_SHADOW_AREA_LIGHT (3)
#define RAYCOUNTVALUES_DIFFUSE_GI_FORWARD (4)
#define RAYCOUNTVALUES_DIFFUSE_GI_DEFERRED (5)
#define RAYCOUNTVALUES_REFLECTION_FORWARD (6)
#define RAYCOUNTVALUES_REFLECTION_DEFERRED (7)
#define RAYCOUNTVALUES_RECURSIVE (8)
#define RAYCOUNTVALUES_COUNT (9)
#define RAYCOUNTVALUES_TOTAL (10)


#endif
