#ifndef BUILTIN_SHADERPASS_INCLUDED
#define BUILTIN_SHADERPASS_INCLUDED

#define SHADERPASS_FORWARD (0)
#define SHADERPASS_GBUFFER (1)
#define SHADERPASS_DEPTHONLY (2)
#define SHADERPASS_SHADOWCASTER (3)
#define SHADERPASS_META (4)
#define SHADERPASS_UNLIT (5)
#define SHADERPASS_SPRITELIT (6)
#define SHADERPASS_SPRITENORMAL (7)
#define SHADERPASS_SPRITEFORWARD (8)
#define SHADERPASS_SPRITEUNLIT (9)
#endif
