//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit > Rendering > Generate Shader Includes ] instead
//

#ifndef MATERIALDEBUG_CS_HLSL
#define MATERIALDEBUG_CS_HLSL
//
// UnityEngine.Rendering.HighDefinition.Attributes.DebugViewGbuffer:  static fields
//
#define DEBUGVIEWGBUFFER_NONE (0)
#define DEBUGVIEWGBUFFER_DEPTH (14)
#define DEBUGVIEWGBUFFER_BAKE_DIFFUSE_LIGHTING_WITH_ALBEDO_PLUS_EMISSIVE (15)
#define DEBUGVIEWGBUFFER_BAKE_SHADOW_MASK0 (16)
#define DEBUGVIEWGBUFFER_BAKE_SHADOW_MASK1 (17)
#define DEBUGVIEWGBUFFER_BAKE_SHADOW_MASK2 (18)
#define DEBUGVIEWGBUFFER_BAKE_SHADOW_MASK3 (19)

//
// UnityEngine.Rendering.HighDefinition.Attributes.DebugViewProperties:  static fields
//
#define DEBUGVIEWPROPERTIES_NONE (0)
#define DEBUGVIEWPROPERTIES_TESSELLATION (20)
#define DEBUGVIEWPROPERTIES_PIXEL_DISPLACEMENT (21)
#define DEBUGVIEWPROPERTIES_VERTEX_DISPLACEMENT (22)
#define DEBUGVIEWPROPERTIES_TESSELLATION_DISPLACEMENT (23)
#define DEBUGVIEWPROPERTIES_DEPTH_OFFSET (24)
#define DEBUGVIEWPROPERTIES_LIGHTMAP (25)
#define DEBUGVIEWPROPERTIES_INSTANCING (26)
#define DEBUGVIEWPROPERTIES_DEFERRED_MATERIALS (27)

//
// UnityEngine.Rendering.HighDefinition.Attributes.DebugViewVarying:  static fields
//
#define DEBUGVIEWVARYING_NONE (0)
#define DEBUGVIEWVARYING_TEXCOORD0 (1)
#define DEBUGVIEWVARYING_TEXCOORD1 (2)
#define DEBUGVIEWVARYING_TEXCOORD2 (3)
#define DEBUGVIEWVARYING_TEXCOORD3 (4)
#define DEBUGVIEWVARYING_TEXCOORD4 (5)
#define DEBUGVIEWVARYING_TEXCOORD5 (6)
#define DEBUGVIEWVARYING_TEXCOORD6 (7)
#define DEBUGVIEWVARYING_TEXCOORD7 (8)
#define DEBUGVIEWVARYING_VERTEX_TANGENT_WS (9)
#define DEBUGVIEWVARYING_VERTEX_BITANGENT_WS (10)
#define DEBUGVIEWVARYING_VERTEX_NORMAL_WS (11)
#define DEBUGVIEWVARYING_VERTEX_COLOR (12)
#define DEBUGVIEWVARYING_VERTEX_COLOR_ALPHA (13)


#endif
