#ifndef HAS_ALPHA
#define CTYPE float3
#define LOAD_COLOR(TEX, COORD) LOAD_TEXTURE2D_X(TEX, COORD).xyz
#define SAMPLE_COLOR_LOD(TEX, SAM, COORD, LOD) SAMPLE_TEXTURE2D_X_LOD(TEX, SAM, COORD, LOD).xyz
#define SAMPLE_COLOR_BICUBIC(A, B, C, D, E, F) SampleTexture2DBicubic(TEXTURE2D_X_ARGS(A, B), C, D, E, F).xyz
#define FETCH_COLOR Fetch
#else
#define CTYPE float4
#define LOAD_COLOR(TEX, COORD) LOAD_TEXTURE2D_X(TEX, COORD)
#define SAMPLE_COLOR_LOD(TEX, SAM, COORD, LOD) SAMPLE_TEXTURE2D_X_LOD(TEX, SAM, COORD, LOD)
#define SAMPLE_COLOR_BICUBIC(A, B, C, D, E, F) SampleTexture2DBicubic(TEXTURE2D_X_ARGS(A, B), C, D, E, F)
#define FETCH_COLOR Fetch4
#endif
