#ifndef UNIVERSAL_PROBE_VOLUME_VARIANTS_INCLUDED
#define UNIVERSAL_PROBE_VOLUME_VARIANTS_INCLUDED

#pragma multi_compile _ PROBE_VOLUMES_L1 PROBE_VOLUMES_L2
#pragma target 4.5 PROBE_VOLUMES_L1
#pragma target 4.5 PROBE_VOLUMES_L2

#endif // UNIVERSAL_PROBE_VOLUME_VARIANTS_INCLUDED
