$Material.KajiyaKay:                #define _MATERIAL_FEATURE_HAIR_KAJIYA_KAY 1
$Material.Marschner:                #define _MATERIAL_FEATURE_HAIR_MARSCHNER 1
$UseLightFacingNormal:              #define _USE_LIGHT_FACING_NORMAL 1
$AmbientOcclusion:                  #define _AMBIENT_OCCLUSION 1
$SpecularOcclusionFromAO:           #define _SPECULAR_OCCLUSION_FROM_AO 1
$SpecularOcclusionFromAOBentNormal: #define _SPECULAR_OCCLUSION_FROM_AO_BENT_NORMAL 1
$SpecularOcclusionCustom:           #define _SPECULAR_OCCLUSION_CUSTOM 1
$Specular.AA:                       #define _ENABLE_GEOMETRIC_SPECULAR_AA 1
$ScatteringDensityVolume:           #define _USE_DENSITY_VOLUME_SCATTERING 1
$UseRoughenedAzimuthalScattering:   #define _USE_ROUGHENED_AZIMUTHAL_SCATTERING 1
