//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef HDRAYTRACINGMANAGER_CS_HLSL
#define HDRAYTRACINGMANAGER_CS_HLSL
//
// UnityEngine.Rendering.HighDefinition.RayTracingRendererFlag:  static fields
//
#define RAYTRACINGRENDERERFLAG_OPAQUE (1)
#define RAYTRACINGRENDERERFLAG_CAST_SHADOW_TRANSPARENT (2)
#define RAYTRACINGRENDERERFLAG_CAST_SHADOW_OPAQUE (4)
#define RAYTRACINGRENDERERFLAG_CAST_SHADOW (6)
#define RAYTRACINGRENDERERFLAG_AMBIENT_OCCLUSION (8)
#define RAYTRACINGRENDERERFLAG_REFLECTION (16)
#define RAYTRACINGRENDERERFLAG_GLOBAL_ILLUMINATION (32)
#define RAYTRACINGRENDERERFLAG_RECURSIVE_RENDERING (64)
#define RAYTRACINGRENDERERFLAG_PATH_TRACING (128)


#endif
