#ifndef UNITY_RAYTRACING_MATERIAL_GBUFFER_MACROS_INCLUDED
#define UNITY_RAYTRACING_MATERIAL_GBUFFER_MACROS_INCLUDED

#ifdef GBUFFERMATERIAL_COUNT

#if GBUFFERMATERIAL_COUNT == 2
#define RAYTRACING_ENCODE_INTO_GBUFFER(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, NAME, FORWARD_ONLY) RayTracingEncodeIntoGBuffer(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, MERGE_NAME(NAME,0), MERGE_NAME(NAME,1), FORWARD_ONLY)

#elif GBUFFERMATERIAL_COUNT == 3

#define RAYTRACING_ENCODE_INTO_GBUFFER(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, NAME, FORWARD_ONLY) RayTracingEncodeIntoGBuffer(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, MERGE_NAME(NAME,0), MERGE_NAME(NAME,1), MERGE_NAME(NAME,2), FORWARD_ONLY)

#elif GBUFFERMATERIAL_COUNT == 4

#define RAYTRACING_ENCODE_INTO_GBUFFER(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, NAME, FORWARD_ONLY) RayTracingEncodeIntoGBuffer(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, MERGE_NAME(NAME, 0), MERGE_NAME(NAME, 1), MERGE_NAME(NAME, 2), MERGE_NAME(NAME, 3), FORWARD_ONLY)

#elif GBUFFERMATERIAL_COUNT == 5

#define RAYTRACING_ENCODE_INTO_GBUFFER(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, NAME, FORWARD_ONLY) RayTracingEncodeIntoGBuffer(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, MERGE_NAME(NAME, 0), MERGE_NAME(NAME, 1), MERGE_NAME(NAME, 2), MERGE_NAME(NAME, 3), MERGE_NAME(NAME, 4), FORWARD_ONLY)

#elif GBUFFERMATERIAL_COUNT == 6

#define RAYTRACING_ENCODE_INTO_GBUFFER(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, NAME, FORWARD_ONLY) RayTracingEncodeIntoGBuffer(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, MERGE_NAME(NAME, 0), MERGE_NAME(NAME, 1), MERGE_NAME(NAME, 2), MERGE_NAME(NAME, 3), MERGE_NAME(NAME, 4), MERGE_NAME(NAME, 5), FORWARD_ONLY)

#elif GBUFFERMATERIAL_COUNT == 7

#define RAYTRACING_ENCODE_INTO_GBUFFER(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, NAME, FORWARD_ONLY) RayTracingEncodeIntoGBuffer(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, MERGE_NAME(NAME, 0), MERGE_NAME(NAME, 1), MERGE_NAME(NAME, 2), MERGE_NAME(NAME, 3), MERGE_NAME(NAME, 4), MERGE_NAME(NAME, 5), MERGE_NAME(NAME, 6), FORWARD_ONLY)

#elif GBUFFERMATERIAL_COUNT == 8

#define RAYTRACING_ENCODE_INTO_GBUFFER(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, NAME, FORWARD_ONLY) RayTracingEncodeIntoGBuffer(SURFACE_DATA, BUILTIN_DATA, UNPOSITIONSS, MERGE_NAME(NAME, 0), MERGE_NAME(NAME, 1), MERGE_NAME(NAME, 2), MERGE_NAME(NAME, 3), MERGE_NAME(NAME, 4), MERGE_NAME(NAME, 5), MERGE_NAME(NAME, 6), MERGE_NAME(NAME, 7), FORWARD_ONLY)

#endif

#endif // #ifdef GBUFFERMATERIAL_COUNT

#endif // UNITY_RAYTRACING_MATERIAL_GBUFFER_MACROS_INCLUDED
