//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef PBRSKYRENDERER_CS_HLSL
#define PBRSKYRENDERER_CS_HLSL
//
// UnityEngine.Experimental.Rendering.HDPipeline.PbrSkyRenderer+PbrSkyConfig:  static fields
//
#define PBRSKYCONFIG_OPTICAL_DEPTH_TABLE_SIZE_X (128)
#define PBRSKYCONFIG_OPTICAL_DEPTH_TABLE_SIZE_Y (128)
#define PBRSKYCONFIG_GROUND_IRRADIANCE_TABLE_SIZE (256)
#define PBRSKYCONFIG_IN_SCATTERED_RADIANCE_TABLE_SIZE_X (128)
#define PBRSKYCONFIG_IN_SCATTERED_RADIANCE_TABLE_SIZE_Y (32)
#define PBRSKYCONFIG_IN_SCATTERED_RADIANCE_TABLE_SIZE_Z (16)
#define PBRSKYCONFIG_IN_SCATTERED_RADIANCE_TABLE_SIZE_W (64)


#endif
