#ifndef UNITY_SPECULAR_OCCLUSION_DEF_INCLUDED
#define UNITY_SPECULAR_OCCLUSION_DEF_INCLUDED

// Specular occlusion methods:
#define SPECULAR_OCCLUSION_DISABLED -1
#define SPECULAR_OCCLUSION_FROM_AO 0
#define SPECULAR_OCCLUSION_CONECONE 1
#define SPECULAR_OCCLUSION_SPTD 2

// Choice of formulas to infer bent visibility: see SPTDistribution.hlsl : GetBentVisibility()
#define BENT_VISIBILITY_FROM_AO_UNIFORM 0
#define BENT_VISIBILITY_FROM_AO_COS 1
#define BENT_VISIBILITY_FROM_AO_COS_BENT_CORRECTION 2

#endif // #define UNITY_SPECULAR_OCCLUSION_DEF_INCLUDED
