#ifndef UNIVERSAL_LIGHT_COOKIE_TYPES_INCLUDED
#define UNIVERSAL_LIGHT_COOKIE_TYPES_INCLUDED

#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/UnityTypes.hlsl"

// Types

#define URP_LIGHT_COOKIE_FORMAT_NONE (-1)
#define URP_LIGHT_COOKIE_FORMAT_RGB (0)
#define URP_LIGHT_COOKIE_FORMAT_ALPHA (1)
#define URP_LIGHT_COOKIE_FORMAT_RED (2)

#endif //UNIVERSAL_LIGHT_COOKIE_TYPES_INCLUDED
