#pragma kernel ClearAtomic

// #pragma enable_d3d11_debug_symbols

#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"

#pragma only_renderers d3d11 playstation xboxone xboxseries vulkan metal switch

RWStructuredBuffer<uint> g_LayeredSingleIdxBuffer : register(u2);     // don't support RWBuffer yet in unity

[numthreads(1, 1, 1)]
void ClearAtomic(uint threadID : SV_GroupIndex, uint3 u3GroupID : SV_GroupID)
{
    g_LayeredSingleIdxBuffer[0]=0;
}
