//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit / Render Pipeline / Generate Shader Includes ] instead
//

#ifndef DEBUGVIEWENUMS_CS_HLSL
#define DEBUGVIEWENUMS_CS_HLSL
//
// UnityEngine.Rendering.Universal.DebugMaterialIndex:  static fields
//
#define DEBUGMATERIALINDEX_NONE (0)
#define DEBUGMATERIALINDEX_UNLIT (1)
#define DEBUGMATERIALINDEX_DIFFUSE (2)
#define DEBUGMATERIALINDEX_SPECULAR (3)
#define DEBUGMATERIALINDEX_ALPHA (4)
#define DEBUGMATERIALINDEX_SMOOTHNESS (5)
#define DEBUGMATERIALINDEX_AMBIENT_OCCLUSION (6)
#define DEBUGMATERIALINDEX_EMISSION (7)
#define DEBUGMATERIALINDEX_NORMAL_WORLD_SPACE (8)
#define DEBUGMATERIALINDEX_NORMAL_TANGENT_SPACE (9)
#define DEBUGMATERIALINDEX_LIGHTING_COMPLEXITY (10)
#define DEBUGMATERIALINDEX_LOD (11)
#define DEBUGMATERIALINDEX_METALLIC (12)

//
// UnityEngine.Rendering.Universal.FullScreenDebugMode:  static fields
//
#define FULLSCREENDEBUGMODE_NONE (0)
#define FULLSCREENDEBUGMODE_DEPTH (1)
#define FULLSCREENDEBUGMODE_ADDITIONAL_LIGHTS_SHADOW_MAP (2)
#define FULLSCREENDEBUGMODE_MAIN_LIGHT_SHADOW_MAP (3)

//
// UnityEngine.Rendering.Universal.SceneOverrides:  static fields
//
#define SCENEOVERRIDES_NONE (0)
#define SCENEOVERRIDES_OVERDRAW (1)
#define SCENEOVERRIDES_WIREFRAME (2)
#define SCENEOVERRIDES_SOLID_WIREFRAME (3)

//
// UnityEngine.Rendering.Universal.LightingDebugMode:  static fields
//
#define LIGHTINGDEBUGMODE_NONE (0)
#define LIGHTINGDEBUGMODE_SHADOW_CASCADES (1)
#define LIGHTINGDEBUGMODE_LIGHT_ONLY (2)
#define LIGHTINGDEBUGMODE_LIGHT_DETAIL (3)
#define LIGHTINGDEBUGMODE_REFLECTIONS (4)
#define LIGHTINGDEBUGMODE_REFLECTIONS_WITH_SMOOTHNESS (5)

//
// UnityEngine.Rendering.Universal.VertexAttributeDebugMode:  static fields
//
#define VERTEXATTRIBUTEDEBUGMODE_NONE (0)
#define VERTEXATTRIBUTEDEBUGMODE_TEXCOORD0 (1)
#define VERTEXATTRIBUTEDEBUGMODE_TEXCOORD1 (2)
#define VERTEXATTRIBUTEDEBUGMODE_TEXCOORD2 (3)
#define VERTEXATTRIBUTEDEBUGMODE_TEXCOORD3 (4)
#define VERTEXATTRIBUTEDEBUGMODE_COLOR (5)
#define VERTEXATTRIBUTEDEBUGMODE_TANGENT (6)
#define VERTEXATTRIBUTEDEBUGMODE_NORMAL (7)

//
// UnityEngine.Rendering.Universal.DebugLightingFeature:  static fields
//
#define DEBUGLIGHTINGFEATURE_NONE (0)
#define DEBUGLIGHTINGFEATURE_GLOBAL_ILLUMINATION (1)
#define DEBUGLIGHTINGFEATURE_MAIN_LIGHT (2)
#define DEBUGLIGHTINGFEATURE_ADDITIONAL_LIGHTS (4)
#define DEBUGLIGHTINGFEATURE_VERTEX_LIGHTING (8)
#define DEBUGLIGHTINGFEATURE_EMISSION (16)
#define DEBUGLIGHTINGFEATURE_AMBIENT_OCCLUSION (32)

//
// UnityEngine.Rendering.Universal.DebugValidationMode:  static fields
//
#define DEBUGVALIDATIONMODE_NONE (0)
#define DEBUGVALIDATIONMODE_HIGHLIGHT_NAN_INF_NEGATIVE (1)
#define DEBUGVALIDATIONMODE_HIGHLIGHT_OUTSIDE_OF_RANGE (2)
#define DEBUGVALIDATIONMODE_VALIDATE_ALBEDO (3)

//
// UnityEngine.Rendering.Universal.DebugMipInfo:  static fields
//
#define DEBUGMIPINFO_NONE (0)
#define DEBUGMIPINFO_LEVEL (1)
#define DEBUGMIPINFO_COUNT (2)


#endif
