#ifndef CORE_CAPSULE_SHADOWS_FLAGS_DEF
#define CORE_CAPSULE_SHADOWS_FLAGS_DEF

#define CAPSULE_OCCLUSION_FLAG_FADE_SELF_SHADOW         (1 << 0)
#define CAPSULE_OCCLUSION_FLAG_INCLUDE_AXIS             (1 << 1)
#define CAPSULE_OCCLUSION_FLAG_RAY_TRACED_REFERENCE     (1 << 2)

#define CAPSULE_AMBIENT_OCCLUSION_FLAG_INCLUDE_AXIS     (1 << 0)
#define CAPSULE_AMBIENT_OCCLUSION_RAY_TRACED_REFERENCE  (1 << 1)

#endif // ndef CORE_CAPSULE_SHADOWS_FLAGS_DEF
