using System.Collections.Generic;

namespace UnityEngine.Rendering.HighDefinition
{
    /// <summary>
    /// Controls the type of the procedural water deformer.
    /// </summary>
    [GenerateHLSL(PackingRules.Exact)]
    public enum WaterDeformerType
    {
        /// <summary>
        /// Sphere deformer.
        /// </summary>
        Sphere = 0,
        /// <summary>
        /// Box deformer.
        /// </summary>
        Box = 1,
        /// <summary>
        /// Bow Wave deformer.
        /// </summary>
        BowWave = 2,
        /// <summary>
        /// Shore Wave deformer.
        /// </summary>
        ShoreWave = 3,
        /// <summary>
        /// Texture Wave deformer.
        /// </summary>
        Texture = 4
    }

    /// <summary>
    /// Water deformer component.
    /// </summary>
    [DisallowMultipleComponent]
    [ExecuteInEditMode]
    public partial class WaterDeformer : MonoBehaviour
    {
        #region General
        /// <summary>
        /// Specifies the type of the deformer. This parameter defines which parameters will be used to render it.
        /// </summary>
        public WaterDeformerType type = WaterDeformerType.Sphere;

        /// <summary>
        /// Specifies the amplitude of the deformer. This parameter is used differently based on the deformer type.
        /// </summary>
        public float amplitude = 2.0f;

        /// <summary>
        /// Specifies the size of the deformer in meters.
        /// </summary>
        public Vector2 regionSize = new Vector2(20.0f, 20.0f);

        /// <summary>
        /// The scaling mode to apply to this Foam Generator.
        /// </summary>
        [Tooltip("Specify the scaling mode")]
        public DecalScaleMode scaleMode = DecalScaleMode.ScaleInvariant;
        #endregion

        #region Box Deformer
        /// <summary>
        /// Specifies the range that is used to blend the box deformer.
        /// </summary>
        [Min(0.0f)]
        public Vector2 boxBlend;

        /// <summary>
        /// When enabled, the box deformer will have a cubic blend on the edges (instead of procedural).
        /// </summary>
        public bool cubicBlend = true;
        #endregion

        #region Shore Wave Deformer
        /// <summary>
        /// Specifies the wave length of the individual waves of the shore wave deformer.
        /// </summary>
        [Min(1.0f)]
        public float waveLength = 3.0f;

        /// <summary>
        /// Specifies the wave repetition of the waves. A higher value implies that additional waves will be skipped.
        /// </summary>
        [Min(1)]
        public int waveRepetition = 10;

        /// <summary>
        /// Specifies the speed of the waves in kilometers per hour.
        /// </summary>
        public float waveSpeed = 15.0f;

        /// <summary>
        /// Specifies the offset in the waves' position.
        /// </summary>
        public float waveOffset = 0.0f;

        /// <summary>
        /// Specifies the blend size on the length of the deformer's region.
        /// </summary>
        public Vector2 waveBlend = new Vector2(0.3f, 0.6f);

        /// <summary>
        /// Specifies the range in which the waves break and generate surface foam.
        /// </summary>
        public Vector2 breakingRange = new Vector2(0.7f, 0.8f);

        /// <summary>
        /// Specifies the range in which the waves generate deep foam.
        /// </summary>
        public Vector2 deepFoamRange = new Vector2(0.5f, 0.8f);
        #endregion

        #region BowWave Deformer
        /// <summary>
        /// Specifies the elevation of outer part of the bow wave.
        /// </summary>
        public float bowWaveElevation = 1.0f;
        #endregion

        #region Texture Deformer
        /// <summary>
        /// Specifies the range of the texture deformer
        /// </summary>
        public Vector2 range = new Vector2(0.0f, 1.0f);

        /// <summary>
        /// Specifies the texture used for the deformer.
        /// </summary>
        public Texture texture = null;
        #endregion

        #region Foam
        /// <summary>
        /// Specifies the dimmer for the deep foam generated by the deformer.
        /// </summary>
        [Range(0.0f, 1.0f)]
        public float deepFoamDimmer = 1.0f;

        /// <summary>
        /// Specifies the dimmer for the surface foam generated by the deformer.
        /// </summary>
        [Range(0.0f, 1.0f)]
        public float surfaceFoamDimmer = 1.0f;
        #endregion

        #region Instance Management
        // Management to avoid memory allocations at fetch time
        internal static HashSet<WaterDeformer> instances = new HashSet<WaterDeformer>();
        internal static WaterDeformer[] instancesAsArray = null;
        internal static int instanceCount = 0;

        internal static void RegisterInstance(WaterDeformer deformer)
        {
            instances.Add(deformer);
            instanceCount = instances.Count;
            if (instanceCount > 0)
            {
                instancesAsArray = new WaterDeformer[instanceCount];
                instances.CopyTo(instancesAsArray);
            }
            else
            {
                instancesAsArray = null;
            }
        }

        internal static void UnregisterInstance(WaterDeformer deformer)
        {
            instances.Remove(deformer);
            instanceCount = instances.Count;
            if (instanceCount > 0)
            {
                instancesAsArray = new WaterDeformer[instanceCount];
                instances.CopyTo(instancesAsArray);
            }
            else
            {
                instancesAsArray = null;
            }
        }
        #endregion

        #region MonoBehavior Methods
        private void Start()
        {
            // Add this water surface to the internal surface management
            RegisterInstance(this);
        }

        private void Awake()
        {
            // Add this water surface to the internal surface management
            RegisterInstance(this);
        }

        private void OnEnable()
        {
            // Add this water surface to the internal surface management
            RegisterInstance(this);
        }

        private void OnDisable()
        {
            // Remove this water surface from the internal surface management
            UnregisterInstance(this);
        }

        void OnDestroy()
        {
            // Remove this water surface from the internal surface management
            UnregisterInstance(this);
        }
        #endregion
    }
}
