uint                                        _LightPerCellCount;
StructuredBuffer<uint>                      _RaytracingLightCluster;
StructuredBuffer<LightData>                 _LightDatasRT;
StructuredBuffer<EnvLightData>              _EnvLightDatasRT;
float3                                      _MinClusterPos;
float3                                      _MaxClusterPos;
uint                                        _PunctualLightCountRT;
uint                                        _AreaLightCountRT;
uint                                        _EnvLightCountRT;
