//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit / Render Pipeline / Generate Shader Includes ] instead
//

#ifndef SHADERCONFIG_CS_HLSL
#define SHADERCONFIG_CS_HLSL
//
// UnityEngine.Rendering.HighDefinition.ProbeVolumesEncodingModes:  static fields
//
#define PROBEVOLUMESENCODINGMODES_SPHERICAL_HARMONICS_L0 (0)
#define PROBEVOLUMESENCODINGMODES_SPHERICAL_HARMONICS_L1 (1)
#define PROBEVOLUMESENCODINGMODES_SPHERICAL_HARMONICS_L2 (2)

//
// UnityEngine.Rendering.HighDefinition.ProbeVolumesBilateralFilteringModes:  static fields
//
#define PROBEVOLUMESBILATERALFILTERINGMODES_DISABLED (0)
#define PROBEVOLUMESBILATERALFILTERINGMODES_VALIDITY (1)
#define PROBEVOLUMESBILATERALFILTERINGMODES_OCTAHEDRAL_DEPTH (2)

//
// UnityEngine.Rendering.HighDefinition.ShaderOptions:  static fields
//
#define SHADEROPTIONS_COLORED_SHADOW (1)
#define SHADEROPTIONS_CAMERA_RELATIVE_RENDERING (1)
#define SHADEROPTIONS_PRE_EXPOSITION (1)
#define SHADEROPTIONS_PRECOMPUTED_ATMOSPHERIC_ATTENUATION (0)
#define SHADEROPTIONS_XR_MAX_VIEWS (2)
#define SHADEROPTIONS_ENABLE_PROBE_VOLUMES (0)
#define SHADEROPTIONS_PROBE_VOLUMES_ADDITIVE_BLENDING (1)
#define SHADEROPTIONS_PROBE_VOLUMES_BILATERAL_FILTERING_MODE (1)
#define SHADEROPTIONS_PROBE_VOLUMES_ENCODING_MODE (1)
#define SHADEROPTIONS_AREA_LIGHTS (1)
#define SHADEROPTIONS_BARN_DOOR (0)


#endif
