#ifndef LIGHTWEIGHT_DEPRECATED_INCLUDED
#define LIGHTWEIGHT_DEPRECATED_INCLUDED

// Stereo-related bits
#define SCREENSPACE_TEXTURE         TEXTURE2D_X
#define SCREENSPACE_TEXTURE_FLOAT   TEXTURE2D_X_FLOAT
#define SCREENSPACE_TEXTURE_HALF    TEXTURE2D_X_HALF

#endif // LIGHTWEIGHT_DEPRECATED_INCLUDED
