<<<<<<< HEAD
#define LWRP_5_14_OR_NEWER
#define LWRP_5_13_OR_NEWER
#define LWRP_5_12_OR_NEWER
#define LWRP_5_11_OR_NEWER
#define LWRP_5_10_OR_NEWER
#define LWRP_5_9_OR_NEWER
#define LWRP_5_8_OR_NEWER
#define LWRP_5_7_OR_NEWER
#define LWRP_5_6_OR_NEWER
#define LWRP_5_5_OR_NEWER
#define LWRP_5_4_OR_NEWER
#define LWRP_5_3_1_OR_NEWER
=======
#define LWRP_7_0_OR_NEWER
#define LWRP_6_7_OR_NEWER
#define LWRP_6_6_OR_NEWER
#define LWRP_6_5_OR_NEWER
#define LWRP_6_4_OR_NEWER
#define LWRP_6_3_OR_NEWER
#define LWRP_6_2_OR_NEWER
#define LWRP_6_1_OR_NEWER
#define LWRP_6_0_OR_NEWER
>>>>>>> master
