//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit / Render Pipeline / Generate Shader Includes ] instead
//

#ifndef SHADERPASS_CS_HLSL
#define SHADERPASS_CS_HLSL
//
// UnityEngine.Rendering.HighDefinition.ShaderPass:  static fields
//
#define SHADERPASS_GBUFFER (0)
#define SHADERPASS_FORWARD (1)
#define SHADERPASS_FORWARD_UNLIT (2)
#define SHADERPASS_DEFERRED_LIGHTING (3)
#define SHADERPASS_DEPTH_ONLY (4)
#define SHADERPASS_TRANSPARENT_DEPTH_PREPASS (5)
#define SHADERPASS_TRANSPARENT_DEPTH_POSTPASS (6)
#define SHADERPASS_MOTION_VECTORS (7)
#define SHADERPASS_DISTORTION (8)
#define SHADERPASS_LIGHT_TRANSPORT (9)
#define SHADERPASS_SHADOWS (10)
#define SHADERPASS_SUBSURFACE_SCATTERING (11)
#define SHADERPASS_VOLUMETRIC_LIGHTING (12)
#define SHADERPASS_DBUFFER_PROJECTOR (13)
#define SHADERPASS_DBUFFER_MESH (14)
#define SHADERPASS_FORWARD_EMISSIVE_PROJECTOR (15)
#define SHADERPASS_FORWARD_EMISSIVE_MESH (16)
#define SHADERPASS_RAYTRACING (17)
#define SHADERPASS_RAYTRACING_INDIRECT (18)
#define SHADERPASS_RAYTRACING_VISIBILITY (19)
#define SHADERPASS_RAYTRACING_FORWARD (20)
#define SHADERPASS_RAYTRACING_GBUFFER (21)
#define SHADERPASS_RAYTRACING_SUB_SURFACE (22)
#define SHADERPASS_PATH_TRACING (23)
#define SHADERPASS_CONSTANT (24)
#define SHADERPASS_FULL_SCREEN_DEBUG (25)


#endif
