//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit > Rendering > Generate Shader Includes ] instead
//

#ifndef SHADERPASS_CS_HLSL
#define SHADERPASS_CS_HLSL
//
// UnityEngine.Rendering.HighDefinition.ShaderPass:  static fields
//
#define SHADERPASS_GBUFFER (0)
#define SHADERPASS_FORWARD (1)
#define SHADERPASS_FORWARD_EMISSIVE_FOR_DEFERRED (2)
#define SHADERPASS_FORWARD_UNLIT (3)
#define SHADERPASS_DEFERRED_LIGHTING (4)
#define SHADERPASS_DEPTH_ONLY (5)
#define SHADERPASS_TRANSPARENT_DEPTH_PREPASS (6)
#define SHADERPASS_TRANSPARENT_DEPTH_POSTPASS (7)
#define SHADERPASS_MOTION_VECTORS (8)
#define SHADERPASS_DISTORTION (9)
#define SHADERPASS_LIGHT_TRANSPORT (10)
#define SHADERPASS_SHADOWS (11)
#define SHADERPASS_SUBSURFACE_SCATTERING (12)
#define SHADERPASS_VOLUMETRIC_LIGHTING (13)
#define SHADERPASS_DBUFFER_PROJECTOR (14)
#define SHADERPASS_DBUFFER_MESH (15)
#define SHADERPASS_FORWARD_EMISSIVE_PROJECTOR (16)
#define SHADERPASS_FORWARD_EMISSIVE_MESH (17)
#define SHADERPASS_RAYTRACING (18)
#define SHADERPASS_RAYTRACING_INDIRECT (19)
#define SHADERPASS_RAYTRACING_VISIBILITY (20)
#define SHADERPASS_RAYTRACING_FORWARD (21)
#define SHADERPASS_RAYTRACING_GBUFFER (22)
#define SHADERPASS_RAYTRACING_SUB_SURFACE (23)
#define SHADERPASS_PATH_TRACING (24)
#define SHADERPASS_CONSTANT (25)
#define SHADERPASS_FULL_SCREEN_DEBUG (26)


#endif
