using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

namespace UnityEngine.Experimental.Rendering.HDPipeline
{
    // All the structures here represent global engine settings.
    // It means that they are supposed to be setup once and not changed during the game.
    // All of these will be serialized in the HDRenderPipelineInstance used for the project.
    [Serializable]
    public class GlobalTextureSettings
    {
        public const int kHDDefaultSpotCookieSize = 128;
        public const int kHDDefaultPointCookieSize = 512;
        public const int kHDDefaultReflectionCubemapSize = 128;

        public int spotCookieSize = kHDDefaultSpotCookieSize;
        public int pointCookieSize = kHDDefaultPointCookieSize;
        public int reflectionCubemapSize = kHDDefaultReflectionCubemapSize;
        public bool reflectionCacheCompressed = false;
    }

    [Serializable]
    public class GlobalRenderingSettings
    {
        public bool useForwardRenderingOnly; // TODO: Currently there is no way to strip the extra forward shaders generated by the shaders compiler, so we can switch dynamically.
        public bool useDepthPrepassWithDeferredRendering;
        public bool renderAlphaTestOnlyInDeferredPrepass;

        // We have to fall back to forward-only rendering when scene view is using wireframe rendering mode --
        // as rendering everything in wireframe + deferred do not play well together
        public bool ShouldUseForwardRenderingOnly()
        {
            return useForwardRenderingOnly || GL.wireframe;
        }
    }
}
